name: Fix Headers for Sitemap

on:
  push:
    branches:
      - main  # nebo master, podle toho, co používáš

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add headers file
        run: |
          mkdir -p ./_headers
          echo "/boudy/sitemap.xml" > ./_headers
          echo "  Content-Type: application/xml" >> ./_headers

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
